/**
 * 各业务模块页面的配置表：标题、描述、字段列、动作与统计卡片。
 *
 * 页面行为统一由 useModulePage + ModulePage 提供，这里只描述差异。
 */
import type { ModulePageConfig } from '@/composables/useModulePage'

export interface ModuleViewConfig extends ModulePageConfig {
  /** 页面大标题，如「检测方法管理」 */
  title: string
  /** 标题下的说明文字 */
  description: string
}

export const MODULE_VIEWS: Record<string, ModuleViewConfig> = {
  sample: {
    module: 'sample',
    label: '样品接收',
    entryName: '检测样品',
    title: '样品接收管理',
    description: '维护检测样品，围绕样品编号、样品名称、委托单位、样品类型做登记、筛选与状态流转。',
    columns: ['样品编号', '样品名称', '委托单位', '样品类型', '接收日期', '保存条件', '送样人员', '接收状态'],
    actions: ['确认接收', '退回样品', '废弃样品'],
    stats: [{ label: '今日接收', value: 0 }, { label: '待接收样品', value: 0 }, { label: '退回样品', value: 0 }],
  },
  task: {
    module: 'task',
    label: '检测任务',
    entryName: '检测任务单',
    title: '检测任务管理',
    description: '维护检测任务单，围绕任务编号、所属样品、检测项目、检测标准做登记、筛选与状态流转。',
    columns: ['任务编号', '所属样品', '检测项目', '检测标准', '指定检测员', '截止日期', '优先级', '任务状态'],
    actions: ['分配任务', '开始检测', '提交复核'],
    stats: [{ label: '待分配任务', value: 0 }, { label: '检测中任务', value: 0 }, { label: '逾期任务', value: 0 }],
  },
  instrument: {
    module: 'instrument',
    label: '仪器管理',
    entryName: '检测仪器',
    title: '仪器管理管理',
    description: '维护检测仪器，围绕仪器编号、仪器名称、型号规格、所属实验室做登记、筛选与状态流转。',
    columns: ['仪器编号', '仪器名称', '型号规格', '所属实验室', '校准周期', '上次校准日', '下次校准日', '仪器状态'],
    actions: ['发起校准', '完成校准', '停用仪器'],
    stats: [{ label: '在用仪器', value: 0 }, { label: '待校准仪器', value: 0 }, { label: '停用仪器', value: 0 }],
  },
  calibration: {
    module: 'calibration',
    label: '校准记录',
    entryName: '校准记录单',
    title: '校准记录管理',
    description: '维护校准记录单，围绕记录编号、仪器编号、校准机构、校准日期做登记、筛选与状态流转。',
    columns: ['记录编号', '仪器编号', '校准机构', '校准日期', '校准结果', '偏差值', '校准证书号', '记录状态'],
    actions: ['执行校准', '标记合格', '标记不合格'],
    stats: [{ label: '待校准记录', value: 0 }, { label: '合格记录', value: 0 }, { label: '不合格记录', value: 0 }],
  },
  reagent: {
    module: 'reagent',
    label: '试剂耗材',
    entryName: '试剂耗材',
    title: '试剂耗材管理',
    description: '维护试剂耗材，围绕试剂编号、试剂名称、规格等级、生产厂家做登记、筛选与状态流转。',
    columns: ['试剂编号', '试剂名称', '规格等级', '生产厂家', '有效期至', '存放位置', '领用人员', '使用状态'],
    actions: ['领用试剂', '登记用完', '标记过期'],
    stats: [{ label: '在库试剂', value: 0 }, { label: '已领用试剂', value: 0 }, { label: '即将过期', value: 0 }],
  },
  result: {
    module: 'result',
    label: '检测结果',
    entryName: '检测结果',
    title: '检测结果管理',
    description: '维护检测结果，围绕结果编号、所属任务、检测项、实测值做登记、筛选与状态流转。',
    columns: ['结果编号', '所属任务', '检测项', '实测值', '标准限值', '判定结论', '检测日期', '结果状态'],
    actions: ['录入结果', '提交审核', '作废结果'],
    stats: [{ label: '待录入结果', value: 0 }, { label: '待审核结果', value: 0 }, { label: '已发布结果', value: 0 }],
  },
  report: {
    module: 'report',
    label: '检测报告',
    entryName: '检测报告',
    title: '检测报告管理',
    description: '维护检测报告，围绕报告编号、委托单位、样品名称、报告类型做登记、筛选与状态流转。',
    columns: ['报告编号', '委托单位', '样品名称', '报告类型', '编制人', '批准人', '签发日期', '报告状态'],
    actions: ['编制报告', '提交批准', '撤回报告'],
    stats: [{ label: '待编制报告', value: 0 }, { label: '待批准报告', value: 0 }, { label: '本月签发', value: 0 }],
  },
  qc: {
    module: 'qc',
    label: '质量控制',
    entryName: '质控样品',
    title: '质量控制管理',
    description: '维护质控样品，围绕质控编号、质控类别、标准值、允许偏差做登记、筛选与状态流转。',
    columns: ['质控编号', '质控类别', '标准值', '允许偏差', '实测值', '判定结果', '检测日期', '质控状态'],
    actions: ['检测质控', '确认受控', '标记失控'],
    stats: [{ label: '待检质控品', value: 0 }, { label: '受控质控品', value: 0 }, { label: '失控质控品', value: 0 }],
  },
  deviation: {
    module: 'deviation',
    label: '偏离处理',
    entryName: '偏离记录',
    title: '偏离处理管理',
    description: '维护偏离记录，围绕偏离编号、偏离描述、涉及样品、发现人做登记、筛选与状态流转。',
    columns: ['偏离编号', '偏离描述', '涉及样品', '发现人', '发现日期', '处理措施', '验证结果', '偏离状态'],
    actions: ['发起调查', '执行处理', '关闭偏离'],
    stats: [{ label: '未关闭偏离', value: 0 }, { label: '调查中偏离', value: 0 }, { label: '本月偏离', value: 0 }],
  },
  sample_storage: {
    module: 'sample_storage',
    label: '样品留存',
    entryName: '留存样品',
    title: '样品留存管理',
    description: '维护留存样品，围绕留存编号、样品编号、留存位置、留存期限做登记、筛选与状态流转。',
    columns: ['留存编号', '样品编号', '留存位置', '留存期限', '到期日期', '保管人员', '处理方式', '留存状态'],
    actions: ['确认处置', '申请延期', '登记处置'],
    stats: [{ label: '留存中样品', value: 0 }, { label: '即将到期', value: 0 }, { label: '已处置样品', value: 0 }],
  },
  contract: {
    module: 'contract',
    label: '委托合同',
    entryName: '委托检验合同',
    title: '委托合同管理',
    description: '维护委托检验合同，围绕合同编号、委托单位、联系人、样品数量做登记、筛选与状态流转。',
    columns: ['合同编号', '委托单位', '联系人', '样品数量', '检测项目', '合同金额', '签约日期', '合同状态'],
    actions: ['签约合同', '终止合同', '确认完成'],
    stats: [{ label: '待签约合同', value: 0 }, { label: '执行中合同', value: 0 }, { label: '本月完成', value: 0 }],
  },
  staff: {
    module: 'staff',
    label: '检测人员',
    entryName: '检测员',
    title: '检测人员管理',
    description: '维护检测员，围绕员工编号、姓名、技术职称、资质证书做登记、筛选与状态流转。',
    columns: ['员工编号', '姓名', '技术职称', '资质证书', '授权项目', '在岗状态', '考核日期', '考核结果'],
    actions: ['安排培训', '确认离岗', '恢复在岗'],
    stats: [{ label: '在岗人员', value: 0 }, { label: '培训中人员', value: 0 }, { label: '离岗人员', value: 0 }],
  },
  method: {
    module: 'method',
    label: '检测方法',
    entryName: '检测方法',
    title: '检测方法管理',
    description: '维护检测方法，围绕方法编号、方法名称、适用标准、检测范围做登记、筛选与状态流转。',
    columns: ['方法编号', '方法名称', '适用标准', '检测范围', '检出限', '方法版本', '批准日期', '方法状态'],
    actions: ['发起验证', '确认有效', '废止方法'],
    stats: [{ label: '现行方法', value: 0 }, { label: '验证中方法', value: 0 }, { label: '废止方法', value: 0 }],
  },
  environment: {
    module: 'environment',
    label: '环境监测',
    entryName: '环境记录',
    title: '环境监测管理',
    description: '维护环境记录，围绕记录编号、监测区域、温度值、湿度值做登记、筛选与状态流转。',
    columns: ['记录编号', '监测区域', '温度值', '湿度值', '压差值', '记录时间', '记录人员', '环境状态'],
    actions: ['登记预警', '确认超标', '标记恢复'],
    stats: [{ label: '正常区域', value: 0 }, { label: '预警区域', value: 0 }, { label: '超标区域', value: 0 }],
  },
  complain: {
    module: 'complain',
    label: '客户申诉',
    entryName: '申诉记录',
    title: '客户申诉管理',
    description: '维护申诉记录，围绕申诉编号、申诉单位、涉及报告、申诉内容做登记、筛选与状态流转。',
    columns: ['申诉编号', '申诉单位', '涉及报告', '申诉内容', '受理日期', '处理结果', '回复日期', '申诉状态'],
    actions: ['受理申诉', '提交答复', '升级仲裁'],
    stats: [{ label: '待受理申诉', value: 0 }, { label: '受理中申诉', value: 0 }, { label: '已答复申诉', value: 0 }],
  },
  audit: {
    module: 'audit',
    label: '内审管理',
    entryName: '内审记录',
    title: '内审管理管理',
    description: '维护内审记录，围绕内审编号、审核范围、审核组长、审核日期做登记、筛选与状态流转。',
    columns: ['内审编号', '审核范围', '审核组长', '审核日期', '不符合项', '纠正期限', '跟踪验证', '内审状态'],
    actions: ['开始内审', '完成内审', '跟踪验证'],
    stats: [{ label: '计划内审', value: 0 }, { label: '进行中内审', value: 0 }, { label: '待跟踪内审', value: 0 }],
  },
  equipment_repair: {
    module: 'equipment_repair',
    label: '仪器维修',
    entryName: '维修记录',
    title: '仪器维修管理',
    description: '维护维修记录，围绕维修编号、仪器编号、故障描述、报修人做登记、筛选与状态流转。',
    columns: ['维修编号', '仪器编号', '故障描述', '报修人', '报修日期', '维修单位', '修复日期', '维修状态'],
    actions: ['派工维修', '确认修复', '标记报废'],
    stats: [{ label: '待维修仪器', value: 0 }, { label: '维修中仪器', value: 0 }, { label: '本月修复', value: 0 }],
  },
  document: {
    module: 'document',
    label: '体系文档',
    entryName: '体系文档',
    title: '体系文档管理',
    description: '维护体系文档，围绕文档编号、文档名称、文档类型、编制人做登记、筛选与状态流转。',
    columns: ['文档编号', '文档名称', '文档类型', '编制人', '版本号', '生效日期', '分发范围', '文档状态'],
    actions: ['提交审批', '正式发布', '作废文档'],
    stats: [{ label: '正式文档', value: 0 }, { label: '审批中文档', value: 0 }, { label: '作废文档', value: 0 }],
  },
}
